//actions types
export const AUTH_GETTING = 'AUTH_GETTING';
export const AUTH_GETSUCCESS = 'AUTH_GETSUCCESS';
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_GETFAIL = 'AUTH_GETFAIL';
export const AUTH_REJECT = 'AUTH_REJECT';

export const AUTH_SIGNUP_SUCCESSED = 'AUTH_SIGNUP_SUCCESSED';
export const AUTH_SIGNUP_FAILED = 'AUTH_SIGNUP_FAILED';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_REJECT = 'AUTH_LOGIN_REJECT';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CHANGE_NAME_SUCCESSED = "CHANGE_NAME_SUCCESSED";

export const ARTICLE_GETTING = 'ARTICLE_GETTING';
export const ARTICLE_GETFAIL = 'ARTICLE_GETFAIL';
export const ARTICLE_GETSUCCESS = 'ARTICLE_GETSUCCESS';
export const ARTICLE_UPDATESUCCESS = 'ARTICLE_UPDATESUCCESS';
export const ARTICLE_INIT = 'ARTICLE_INIT';