//actions types
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_GETTING = 'AUTH_GETTING';
export const AUTH_GETSUCCESS = 'AUTH_GETSUCCESS';
export const AUTH_GETFAIL = 'AUTH_GETFAIL';
export const AUTH_REJECT = 'AUTH_REJECT';

export const AUTH_SIGNUP_SUCCESSED = 'AUTH_SIGNUP_SUCCESSED';
export const AUTH_SIGNUP_FAILED = 'AUTH_SIGNUP_FAILED';
export const AUTH_SIGNUP_INIT = 'AUTH_SIGNUP_INIT';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_REJECT = 'AUTH_LOGIN_REJECT';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
